[package]
name = "robot-explorer"
version = "0.1.0"
authors = ["Samuel Brolia <samuel_brolia@msn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
